# coding: utf-8
"""
    YNAB API Endpoints

    Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

    The version of the OpenAPI document: 1.68.0
    Generated by: https://konfigthis.com
"""

import typing
import inspect
from datetime import date, datetime
from ynab_python_sdk.client_custom import ClientCustom
from ynab_python_sdk.configuration import Configuration
from ynab_python_sdk.api_client import ApiClient
from ynab_python_sdk.type_util import copy_signature
from ynab_python_sdk.apis.tags.accounts_api import AccountsApi
from ynab_python_sdk.apis.tags.budgets_api import BudgetsApi
from ynab_python_sdk.apis.tags.categories_api import CategoriesApi
from ynab_python_sdk.apis.tags.months_api import MonthsApi
from ynab_python_sdk.apis.tags.payee_locations_api import PayeeLocationsApi
from ynab_python_sdk.apis.tags.payees_api import PayeesApi
from ynab_python_sdk.apis.tags.scheduled_transactions_api import ScheduledTransactionsApi
from ynab_python_sdk.apis.tags.transactions_api import TransactionsApi
from ynab_python_sdk.apis.tags.user_api import UserApi



class Ynab(ClientCustom):

    def __init__(self, configuration: typing.Union[Configuration, None] = None, **kwargs):
        super().__init__(configuration, **kwargs)
        if (len(kwargs) > 0):
            configuration = Configuration(**kwargs)
        if (configuration is None):
            raise Exception("configuration is required")
        api_client = ApiClient(configuration)
        self.accounts: AccountsApi = AccountsApi(api_client)
        self.budgets: BudgetsApi = BudgetsApi(api_client)
        self.categories: CategoriesApi = CategoriesApi(api_client)
        self.months: MonthsApi = MonthsApi(api_client)
        self.payee_locations: PayeeLocationsApi = PayeeLocationsApi(api_client)
        self.payees: PayeesApi = PayeesApi(api_client)
        self.scheduled_transactions: ScheduledTransactionsApi = ScheduledTransactionsApi(api_client)
        self.transactions: TransactionsApi = TransactionsApi(api_client)
        self.user: UserApi = UserApi(api_client)
