# coding: utf-8

"""
    YNAB API Endpoints

    Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

    The version of the OpenAPI document: 1.68.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from ynab_python_sdk.pydantic.account import Account
from ynab_python_sdk.pydantic.currency_format import CurrencyFormat
from ynab_python_sdk.pydantic.date_format import DateFormat

class BudgetSummary(BaseModel):
    id: str = Field(alias='id')

    name: str = Field(alias='name')

    # The last time any changes were made to the budget from either a web or mobile client
    last_modified_on: typing.Optional[datetime] = Field(None, alias='last_modified_on')

    # The earliest budget month
    first_month: typing.Optional[date] = Field(None, alias='first_month')

    # The latest budget month
    last_month: typing.Optional[date] = Field(None, alias='last_month')

    date_format: typing.Optional[DateFormat] = Field(None, alias='date_format')

    currency_format: typing.Optional[CurrencyFormat] = Field(None, alias='currency_format')

    # The budget accounts (only included if `include_accounts=true` specified as query parameter)
    accounts: typing.Optional[typing.List[Account]] = Field(None, alias='accounts')
    class Config:
        arbitrary_types_allowed = True
