# coding: utf-8

"""
    YNAB API Endpoints

    Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

    The version of the OpenAPI document: 1.68.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class Category(BaseModel):
    id: str = Field(alias='id')

    category_group_id: str = Field(alias='category_group_id')

    name: str = Field(alias='name')

    # Whether or not the category is hidden
    hidden: bool = Field(alias='hidden')

    # Budgeted amount in milliunits format
    budgeted: int = Field(alias='budgeted')

    # Activity amount in milliunits format
    activity: int = Field(alias='activity')

    # Balance in milliunits format
    balance: int = Field(alias='balance')

    # Whether or not the category has been deleted.  Deleted categories will only be included in delta requests.
    deleted: bool = Field(alias='deleted')

    category_group_name: typing.Optional[str] = Field(None, alias='category_group_name')

    # DEPRECATED: No longer used.  Value will always be null.
    original_category_group_id: typing.Optional[typing.Optional[str]] = Field(None, alias='original_category_group_id')

    note: typing.Optional[typing.Optional[str]] = Field(None, alias='note')

    # The type of goal, if the category has a goal (TB='Target Category Balance', TBD='Target Category Balance by Date', MF='Monthly Funding', NEED='Plan Your Spending')
    goal_type: typing.Optional[Literal["TB", "TBD", "MF", "NEED", "DEBT", None]] = Field(None, alias='goal_type')

    # A day offset modifier for the goal's due date. When goal_cadence is 2 (Weekly), this value specifies which day of the week the goal is due (0 = Sunday, 6 = Saturday). Otherwise, this value specifies which day of the month the goal is due (1 = 1st, 31 = 31st, null = Last day of Month).
    goal_day: typing.Optional[typing.Optional[int]] = Field(None, alias='goal_day')

    # The goal cadence. Value in range 0-14. There are two subsets of these values which behave differently. For values 0, 1, 2, and 13, the goal's due date repeats every goal_cadence * goal_cadence_frequency, where 0 = None, 1 = Monthly, 2 = Weekly, and 13 = Yearly. For example, goal_cadence 1 with goal_cadence_frequency 2 means the goal is due every other month. For values 3-12 and 14, goal_cadence_frequency is ignored and the goal's due date repeats every goal_cadence, where 3 = Every 2 Months, 4 = Every 3 Months, ..., 12 = Every 11 Months, and 14 = Every 2 Years.
    goal_cadence: typing.Optional[typing.Optional[int]] = Field(None, alias='goal_cadence')

    # The goal cadence frequency. When goal_cadence is 0, 1, 2, or 13, a goal's due date repeats every goal_cadence * goal_cadence_frequency. For example, goal_cadence 1 with goal_cadence_frequency 2 means the goal is due every other month.  When goal_cadence is 3-12 or 14, goal_cadence_frequency is ignored.
    goal_cadence_frequency: typing.Optional[typing.Optional[int]] = Field(None, alias='goal_cadence_frequency')

    # The month a goal was created
    goal_creation_month: typing.Optional[typing.Optional[date]] = Field(None, alias='goal_creation_month')

    # The goal target amount in milliunits
    goal_target: typing.Optional[typing.Optional[int]] = Field(None, alias='goal_target')

    # The original target month for the goal to be completed.  Only some goal types specify this date.
    goal_target_month: typing.Optional[typing.Optional[date]] = Field(None, alias='goal_target_month')

    # The percentage completion of the goal
    goal_percentage_complete: typing.Optional[typing.Optional[int]] = Field(None, alias='goal_percentage_complete')

    # The number of months, including the current month, left in the current goal period.
    goal_months_to_budget: typing.Optional[typing.Optional[int]] = Field(None, alias='goal_months_to_budget')

    # The amount of funding still needed in the current month to stay on track towards completing the goal within the current goal period. This amount will generally correspond to the 'Underfunded' amount in the web and mobile clients except when viewing a category with a Needed for Spending Goal in a future month.  The web and mobile clients will ignore any funding from a prior goal period when viewing category with a Needed for Spending Goal in a future month.
    goal_under_funded: typing.Optional[typing.Optional[int]] = Field(None, alias='goal_under_funded')

    # The total amount funded towards the goal within the current goal period.
    goal_overall_funded: typing.Optional[typing.Optional[int]] = Field(None, alias='goal_overall_funded')

    # The amount of funding still needed to complete the goal within the current goal period.
    goal_overall_left: typing.Optional[typing.Optional[int]] = Field(None, alias='goal_overall_left')
    class Config:
        arbitrary_types_allowed = True
