# coding: utf-8

"""
    YNAB API Endpoints

    Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

    The version of the OpenAPI document: 1.68.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from ynab_python_sdk.pydantic.account_type import AccountType

class SaveAccount(BaseModel):
    # The name of the account
    name: str = Field(alias='name')

    type: AccountType = Field(alias='type')

    # The current balance of the account in milliunits format
    balance: int = Field(alias='balance')
    class Config:
        arbitrary_types_allowed = True
