# coding: utf-8

"""
    YNAB API Endpoints

    Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

    The version of the OpenAPI document: 1.68.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel


class SubTransaction(BaseModel):
    id: str = Field(alias='id')

    transaction_id: str = Field(alias='transaction_id')

    # The subtransaction amount in milliunits format
    amount: int = Field(alias='amount')

    # Whether or not the subtransaction has been deleted.  Deleted subtransactions will only be included in delta requests.
    deleted: bool = Field(alias='deleted')

    memo: typing.Optional[typing.Optional[str]] = Field(None, alias='memo')

    payee_id: typing.Optional[typing.Optional[str]] = Field(None, alias='payee_id')

    payee_name: typing.Optional[typing.Optional[str]] = Field(None, alias='payee_name')

    category_id: typing.Optional[typing.Optional[str]] = Field(None, alias='category_id')

    category_name: typing.Optional[typing.Optional[str]] = Field(None, alias='category_name')

    # If a transfer, the account_id which the subtransaction transfers to
    transfer_account_id: typing.Optional[typing.Optional[str]] = Field(None, alias='transfer_account_id')

    # If a transfer, the id of transaction on the other side of the transfer
    transfer_transaction_id: typing.Optional[typing.Optional[str]] = Field(None, alias='transfer_transaction_id')
    class Config:
        arbitrary_types_allowed = True
