# coding: utf-8

"""
    YNAB API Endpoints

    Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

    The version of the OpenAPI document: 1.68.0
    Generated by: https://konfigthis.com
"""

import unittest

import ynab_python_sdk
from ynab_python_sdk.model.transaction_flag_name import TransactionFlagName
from ynab_python_sdk import configuration


class TestTransactionFlagName(unittest.TestCase):
    """TransactionFlagName unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
