# coding: utf-8

"""
    YNAB API Endpoints

    Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

    The version of the OpenAPI document: 1.68.0
    Generated by: https://konfigthis.com
"""

from ynab_python_sdk.paths.budgets_budget_id.get import GetBudget
from ynab_python_sdk.paths.budgets_budget_id_settings.get import GetSettings
from ynab_python_sdk.paths.budgets.get import ListSummary
from ynab_python_sdk.apis.tags.budgets_api_raw import BudgetsApiRaw


class BudgetsApi(
    GetBudget,
    GetSettings,
    ListSummary,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: BudgetsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = BudgetsApiRaw(api_client)
