# coding: utf-8

"""
    YNAB API Endpoints

    Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

    The version of the OpenAPI document: 1.68.0
    Generated by: https://konfigthis.com
"""

from ynab_python_sdk.paths.budgets_budget_id_months_month.get import GetSingle
from ynab_python_sdk.paths.budgets_budget_id_months.get import List
from ynab_python_sdk.apis.tags.months_api_raw import MonthsApiRaw


class MonthsApi(
    GetSingle,
    List,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: MonthsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = MonthsApiRaw(api_client)
