# coding: utf-8

"""
    YNAB API Endpoints

    Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

    The version of the OpenAPI document: 1.68.0
    Generated by: https://konfigthis.com
"""

from ynab_python_sdk.paths.budgets_budget_id_payee_locations_payee_location_id.get import GetSingle
from ynab_python_sdk.paths.budgets_budget_id_payee_locations.get import ListAll
from ynab_python_sdk.paths.budgets_budget_id_payees_payee_id_payee_locations.get import ListByPayee
from ynab_python_sdk.apis.tags.payee_locations_api_raw import PayeeLocationsApiRaw


class PayeeLocationsApi(
    GetSingle,
    ListAll,
    ListByPayee,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: PayeeLocationsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = PayeeLocationsApiRaw(api_client)
