# coding: utf-8

"""
    YNAB API Endpoints

    Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

    The version of the OpenAPI document: 1.68.0
    Generated by: https://konfigthis.com
"""

from ynab_python_sdk.paths.budgets_budget_id_transactions.post import CreateSingleOrMultiple
from ynab_python_sdk.paths.budgets_budget_id_transactions_transaction_id.delete import DeleteExistingTransaction
from ynab_python_sdk.paths.budgets_budget_id_transactions_transaction_id.get import GetSingleTransaction
from ynab_python_sdk.paths.budgets_budget_id_transactions_import.post import ImportLinkedAccounts
from ynab_python_sdk.paths.budgets_budget_id_accounts_account_id_transactions.get import ListByAccount
from ynab_python_sdk.paths.budgets_budget_id_categories_category_id_transactions.get import ListByCategory
from ynab_python_sdk.paths.budgets_budget_id_payees_payee_id_transactions.get import ListByPayee
from ynab_python_sdk.paths.budgets_budget_id_transactions.get import ListTransactions
from ynab_python_sdk.paths.budgets_budget_id_transactions_transaction_id.put import UpdateExistingTransaction
from ynab_python_sdk.paths.budgets_budget_id_transactions.patch import UpdateMultiple
from ynab_python_sdk.apis.tags.transactions_api_raw import TransactionsApiRaw


class TransactionsApi(
    CreateSingleOrMultiple,
    DeleteExistingTransaction,
    GetSingleTransaction,
    ImportLinkedAccounts,
    ListByAccount,
    ListByCategory,
    ListByPayee,
    ListTransactions,
    UpdateExistingTransaction,
    UpdateMultiple,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: TransactionsApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = TransactionsApiRaw(api_client)
