# coding: utf-8

"""
    YNAB API Endpoints

    Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

    The version of the OpenAPI document: 1.68.0
    Generated by: https://konfigthis.com
"""

from ynab_python_sdk.paths.budgets_budget_id_transactions.post import CreateSingleOrMultipleRaw
from ynab_python_sdk.paths.budgets_budget_id_transactions_transaction_id.delete import DeleteExistingTransactionRaw
from ynab_python_sdk.paths.budgets_budget_id_transactions_transaction_id.get import GetSingleTransactionRaw
from ynab_python_sdk.paths.budgets_budget_id_transactions_import.post import ImportLinkedAccountsRaw
from ynab_python_sdk.paths.budgets_budget_id_accounts_account_id_transactions.get import ListByAccountRaw
from ynab_python_sdk.paths.budgets_budget_id_categories_category_id_transactions.get import ListByCategoryRaw
from ynab_python_sdk.paths.budgets_budget_id_payees_payee_id_transactions.get import ListByPayeeRaw
from ynab_python_sdk.paths.budgets_budget_id_transactions.get import ListTransactionsRaw
from ynab_python_sdk.paths.budgets_budget_id_transactions_transaction_id.put import UpdateExistingTransactionRaw
from ynab_python_sdk.paths.budgets_budget_id_transactions.patch import UpdateMultipleRaw


class TransactionsApiRaw(
    CreateSingleOrMultipleRaw,
    DeleteExistingTransactionRaw,
    GetSingleTransactionRaw,
    ImportLinkedAccountsRaw,
    ListByAccountRaw,
    ListByCategoryRaw,
    ListByPayeeRaw,
    ListTransactionsRaw,
    UpdateExistingTransactionRaw,
    UpdateMultipleRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
