# coding: utf-8

"""
    YNAB API Endpoints

    Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

    The version of the OpenAPI document: 1.68.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from ynab_python_sdk.type.account import Account
from ynab_python_sdk.type.budget_summary import BudgetSummary
from ynab_python_sdk.type.category import Category
from ynab_python_sdk.type.category_group import CategoryGroup
from ynab_python_sdk.type.month_detail import MonthDetail
from ynab_python_sdk.type.payee import Payee
from ynab_python_sdk.type.payee_location import PayeeLocation
from ynab_python_sdk.type.scheduled_sub_transaction import ScheduledSubTransaction
from ynab_python_sdk.type.scheduled_transaction_summary import ScheduledTransactionSummary
from ynab_python_sdk.type.sub_transaction import SubTransaction
from ynab_python_sdk.type.transaction_summary import TransactionSummary

BudgetDetail = typing.Union[BudgetSummary,typing.Dict[str, typing.Union[bool, date, datetime, dict, float, int, list, str, None]]]
