# coding: utf-8

"""
    YNAB API Endpoints

    Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

    The version of the OpenAPI document: 1.68.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING


class RequiredCurrencyFormat(TypedDict):
    iso_code: str

    example_format: str

    decimal_digits: int

    decimal_separator: str

    symbol_first: bool

    group_separator: str

    currency_symbol: str

    display_symbol: bool

class OptionalCurrencyFormat(TypedDict, total=False):
    pass

class CurrencyFormat(RequiredCurrencyFormat, OptionalCurrencyFormat):
    pass
