# coding: utf-8

"""
    YNAB API Endpoints

    Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

    The version of the OpenAPI document: 1.68.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING

from ynab_python_sdk.type.transaction_flag_color import TransactionFlagColor
from ynab_python_sdk.type.transaction_flag_name import TransactionFlagName

class RequiredScheduledTransactionSummary(TypedDict):
    id: str

    # The first date for which the Scheduled Transaction was scheduled.
    date_first: date

    # The next date for which the Scheduled Transaction is scheduled.
    date_next: date

    frequency: str

    # The scheduled transaction amount in milliunits format
    amount: int

    account_id: str

    # Whether or not the scheduled transaction has been deleted.  Deleted scheduled transactions will only be included in delta requests.
    deleted: bool

class OptionalScheduledTransactionSummary(TypedDict, total=False):
    memo: typing.Optional[str]

    flag_color: TransactionFlagColor

    flag_name: TransactionFlagName

    payee_id: typing.Optional[str]

    category_id: typing.Optional[str]

    # If a transfer, the account_id which the scheduled transaction transfers to
    transfer_account_id: typing.Optional[str]

class ScheduledTransactionSummary(RequiredScheduledTransactionSummary, OptionalScheduledTransactionSummary):
    pass
