# coding: utf-8

"""
    YNAB API Endpoints

    Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

    The version of the OpenAPI document: 1.68.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from ynab_python_sdk import schemas  # noqa: F401


class SaveTransactionsResponseData(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "server_knowledge",
            "transaction_ids",
        }
        
        class properties:
        
            @staticmethod
            def transaction_ids() -> typing.Type['SaveTransactionsResponseDataTransactionIds']:
                return SaveTransactionsResponseDataTransactionIds
            server_knowledge = schemas.Int64Schema
        
            @staticmethod
            def transaction() -> typing.Type['TransactionDetail']:
                return TransactionDetail
            
            
            class transactions(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['TransactionDetail']:
                        return TransactionDetail
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['TransactionDetail'], typing.List['TransactionDetail']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'transactions':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'TransactionDetail':
                    return super().__getitem__(i)
        
            @staticmethod
            def duplicate_import_ids() -> typing.Type['SaveTransactionsResponseDataDuplicateImportIds']:
                return SaveTransactionsResponseDataDuplicateImportIds
            __annotations__ = {
                "transaction_ids": transaction_ids,
                "server_knowledge": server_knowledge,
                "transaction": transaction,
                "transactions": transactions,
                "duplicate_import_ids": duplicate_import_ids,
            }
    
    server_knowledge: MetaOapg.properties.server_knowledge
    transaction_ids: 'SaveTransactionsResponseDataTransactionIds'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["transaction_ids"]) -> 'SaveTransactionsResponseDataTransactionIds': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["server_knowledge"]) -> MetaOapg.properties.server_knowledge: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["transaction"]) -> 'TransactionDetail': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["transactions"]) -> MetaOapg.properties.transactions: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["duplicate_import_ids"]) -> 'SaveTransactionsResponseDataDuplicateImportIds': ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["transaction_ids", "server_knowledge", "transaction", "transactions", "duplicate_import_ids", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["transaction_ids"]) -> 'SaveTransactionsResponseDataTransactionIds': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["server_knowledge"]) -> MetaOapg.properties.server_knowledge: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["transaction"]) -> typing.Union['TransactionDetail', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["transactions"]) -> typing.Union[MetaOapg.properties.transactions, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["duplicate_import_ids"]) -> typing.Union['SaveTransactionsResponseDataDuplicateImportIds', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["transaction_ids", "server_knowledge", "transaction", "transactions", "duplicate_import_ids", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        server_knowledge: typing.Union[MetaOapg.properties.server_knowledge, decimal.Decimal, int, ],
        transaction_ids: 'SaveTransactionsResponseDataTransactionIds',
        transaction: typing.Union['TransactionDetail', schemas.Unset] = schemas.unset,
        transactions: typing.Union[MetaOapg.properties.transactions, list, tuple, schemas.Unset] = schemas.unset,
        duplicate_import_ids: typing.Union['SaveTransactionsResponseDataDuplicateImportIds', schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'SaveTransactionsResponseData':
        return super().__new__(
            cls,
            *args,
            server_knowledge=server_knowledge,
            transaction_ids=transaction_ids,
            transaction=transaction,
            transactions=transactions,
            duplicate_import_ids=duplicate_import_ids,
            _configuration=_configuration,
            **kwargs,
        )

from ynab_python_sdk.model.save_transactions_response_data_duplicate_import_ids import SaveTransactionsResponseDataDuplicateImportIds
from ynab_python_sdk.model.save_transactions_response_data_transaction_ids import SaveTransactionsResponseDataTransactionIds
from ynab_python_sdk.model.transaction_detail import TransactionDetail
