# coding: utf-8

"""
    YNAB API Endpoints

    Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

    The version of the OpenAPI document: 1.68.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from ynab_python_sdk import schemas  # noqa: F401


class ScheduledTransactionsResponseData(
    schemas.DictSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)
    """


    class MetaOapg:
        required = {
            "scheduled_transactions",
            "server_knowledge",
        }
        
        class properties:
            
            
            class scheduled_transactions(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    
                    @staticmethod
                    def items() -> typing.Type['ScheduledTransactionDetail']:
                        return ScheduledTransactionDetail
            
                def __new__(
                    cls,
                    arg: typing.Union[typing.Tuple['ScheduledTransactionDetail'], typing.List['ScheduledTransactionDetail']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'scheduled_transactions':
                    return super().__new__(
                        cls,
                        arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'ScheduledTransactionDetail':
                    return super().__getitem__(i)
            server_knowledge = schemas.Int64Schema
            __annotations__ = {
                "scheduled_transactions": scheduled_transactions,
                "server_knowledge": server_knowledge,
            }
    
    scheduled_transactions: MetaOapg.properties.scheduled_transactions
    server_knowledge: MetaOapg.properties.server_knowledge
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["scheduled_transactions"]) -> MetaOapg.properties.scheduled_transactions: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["server_knowledge"]) -> MetaOapg.properties.server_knowledge: ...
    
    @typing.overload
    def __getitem__(self, name: str) -> schemas.UnsetAnyTypeSchema: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["scheduled_transactions", "server_knowledge", ], str]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["scheduled_transactions"]) -> MetaOapg.properties.scheduled_transactions: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["server_knowledge"]) -> MetaOapg.properties.server_knowledge: ...
    
    @typing.overload
    def get_item_oapg(self, name: str) -> typing.Union[schemas.UnsetAnyTypeSchema, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["scheduled_transactions", "server_knowledge", ], str]):
        return super().get_item_oapg(name)
    

    def __new__(
        cls,
        *args: typing.Union[dict, frozendict.frozendict, ],
        scheduled_transactions: typing.Union[MetaOapg.properties.scheduled_transactions, list, tuple, ],
        server_knowledge: typing.Union[MetaOapg.properties.server_knowledge, decimal.Decimal, int, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
        **kwargs: typing.Union[schemas.AnyTypeSchema, dict, frozendict.frozendict, str, date, datetime, uuid.UUID, int, float, decimal.Decimal, None, list, tuple, bytes],
    ) -> 'ScheduledTransactionsResponseData':
        return super().__new__(
            cls,
            *args,
            scheduled_transactions=scheduled_transactions,
            server_knowledge=server_knowledge,
            _configuration=_configuration,
            **kwargs,
        )

from ynab_python_sdk.model.scheduled_transaction_detail import ScheduledTransactionDetail
