# coding: utf-8

"""
    YNAB API Endpoints

    Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

    The version of the OpenAPI document: 1.68.0
    Generated by: https://konfigthis.com
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from ynab_python_sdk import schemas  # noqa: F401


class TransactionClearedStatus(
    schemas.EnumBase,
    schemas.StrSchema
):
    """
    This class is auto generated by Konfig (https://konfigthis.com)

    The cleared status of the transaction
    """


    class MetaOapg:
        enum_value_to_name = {
            "cleared": "CLEARED",
            "uncleared": "UNCLEARED",
            "reconciled": "RECONCILED",
        }
    
    @schemas.classproperty
    def CLEARED(cls):
        return cls("cleared")
    
    @schemas.classproperty
    def UNCLEARED(cls):
        return cls("uncleared")
    
    @schemas.classproperty
    def RECONCILED(cls):
        return cls("reconciled")
